"""
Resource package with loaders generated by resourcepackage from
resourcepackages.sf.net.

Remember to use the wx version when adding resources (uncomment
two lines in the default resourcepackage __init__.py)
"""
