#!/usr/bin/env python
import sys,os
import os.path
from optparse import OptionParser

def reexec_with_pythonw():
    if sys.platform == 'darwin' and\
           not sys.executable.endswith('MacOS/Python'):
        print >>sys.stderr,'re-executing using pythonw'
        os.execvp('pythonw',['pythonw',__file__] + sys.argv[1:])

parser = OptionParser()
parser.add_option('--devel',action='store_true',dest='devel',
                  help='run in development mode (does not use installed version)')
parser.add_option('--disable_pythonw',action='store_true',dest='no_pythonw',
                  help='disable automatically running pythonw on Mac')
parser.add_option('-v','--version',action='store_true',dest='version',
                  help='Display neveredit version')

options,args = parser.parse_args()
    
if not options.no_pythonw:
    reexec_with_pythonw()
    
import neveredit,neveredit.ui.NeverEditMainApp

if options.version:
    print 'neveredit module at',neveredit.__file__
    print 'neveredit version',neveredit.__version__
    sys.exit()
    
print 'Using main class from:',neveredit.ui.NeverEditMainApp.__file__
neveredit.ui.NeverEditMainApp.run(args)
